### ISSUE TITLE
Aerial won't close when turning off computer

### ISSUE THREAD

**Issue by Kevin64** [ChrisAnd1998/Aerial#1]
When turning off or restarting the PC, Aerial will keep itself open and Windows shows the message that 'Btop' (which is Aerial.exe) is preventing the shutdown/restart. We have to click the 'shut down anyway' or 'restart anyway' to complete the process.

**Comment by ChrisAnd1998** [comment]
You're probably using version 1.0.3.0.
Please use 1.0.4.0 pre-release. Which is the new rewritten version ;)

https://github.com/ChrisAnd1998/Aerial/releases/tag/1.0.4.0

**Comment by Kevin64** [comment]
Oh, okay. I'm using the Store version, but the update is not there still. I can wait a few more days for it. Thanks :)

**Comment by ChrisAnd1998** [comment]
It seems to work stable but, i want to do some more testing before i make it a release and publish it to the store.
